import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossOrigin="anonymous"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">
          <div className="row">
            <div className="col">
              <Link href="/">Home</Link> &nbsp;
              <Link href="/about">About</Link> &nbsp;
              <Link href="/contact">Contact</Link> &nbsp;
            </div>
          </div>
          <div className="row">
            <div className="col-3">
              Sidebar
            </div>
            <div className="col">
              {
                children
              }
            </div>
          </div>
          <div className="row">
            <div className="col">
              Footer
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
